server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

spring.application.name: user-service